// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhr8iO8uk1ADGwVL39nGcprMBUaHtvx58',
    appId: '1:980320313937:web:4267c338b8f60974460e70',
    messagingSenderId: '980320313937',
    projectId: 'learning-app-239c6',
    authDomain: 'learning-app-239c6.firebaseapp.com',
    storageBucket: 'learning-app-239c6.firebasestorage.app',
    measurementId: 'G-K4Z0H5RZCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa32D0s5dTDTsWPdG5V9QkNG4RiHkSb8U',
    appId: '1:980320313937:android:5d3d35ebc21ac6b3460e70',
    messagingSenderId: '980320313937',
    projectId: 'learning-app-239c6',
    storageBucket: 'learning-app-239c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdeKs1oJdh-0V6o3zrQvgbPtexMO4QQTw',
    appId: '1:980320313937:ios:5b8f0c6739359230460e70',
    messagingSenderId: '980320313937',
    projectId: 'learning-app-239c6',
    storageBucket: 'learning-app-239c6.firebasestorage.app',
    iosBundleId: 'com.example.learningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdeKs1oJdh-0V6o3zrQvgbPtexMO4QQTw',
    appId: '1:980320313937:ios:5b8f0c6739359230460e70',
    messagingSenderId: '980320313937',
    projectId: 'learning-app-239c6',
    storageBucket: 'learning-app-239c6.firebasestorage.app',
    iosBundleId: 'com.example.learningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhr8iO8uk1ADGwVL39nGcprMBUaHtvx58',
    appId: '1:980320313937:web:ca25c61aa307707f460e70',
    messagingSenderId: '980320313937',
    projectId: 'learning-app-239c6',
    authDomain: 'learning-app-239c6.firebaseapp.com',
    storageBucket: 'learning-app-239c6.firebasestorage.app',
    measurementId: 'G-XW179EHN3W',
  );
}
